FROM nginx:latest

# Setup conf.d/default.conf
RUN rm /etc/nginx/conf.d/default.conf
COPY conf.d/default.conf /etc/nginx/conf.d/

# Insert HTML files
COPY html /usr/share/nginx/html

# Define environment variables

# Expose ports

# Init?

